name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Tencent coscmd
        run: |
          sudo pip install coscmd

      - name: Configure Tencent coscmd
        env:
          SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
          BUCKET: wiki-1253454583
          REGION: ap-guangzhou
        run: |
          coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION

      - name: Deploy static to Tencent COS
        run: |
          coscmd upload -rfs --delete -f . /

